# This GUI layout was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
# GUI design and code by Dylan Nguyen

from pathlib import Path
from FitnessTracker.my_validations import get_vcmd
import subprocess
# Explicit imports to satisfy Flake8
from tkinter import Toplevel, Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("gui/build/assets/frame0")    # Change this for each 4 files. "W:\...\FitnessTracker\main\gui\build\assets\frame0" where W is where you save it.


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def run_script(gui):
    root.withdraw()
    try:
        # Run the new script and wait for it to finish
        subprocess.run(["python", "gui/build/"+gui], check=True)
    except:
        try:
            subprocess.run(["python", "FitnessTracker/gui/build/" + gui], check=True)
        except subprocess.CalledProcessError as e:
            print(f"Error occurred while running bw_gui.py: {e}")
    finally:
        # Show the main window again after the script finishes
        root.deiconify()


root = Tk()
root.title("Home GUI")
root.geometry("800x600")
root.configure(bg = "#395271")


canvas = Canvas(
    root,
    bg = "#395271",
    height = 600,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
muscle_button = Button(     # Muscle -> short for muscle_measurement
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: [print("muscle_measurements clicked"), run_script("measure_gui.py")],
    relief="flat"
)
muscle_button.place(
    x=97.0,
    y=93.0,
    width=272.0,
    height=182.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
max_reps_button = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: [print("max_reps clicked"), run_script("max_rep_gui.py")],
    relief="flat"
)
max_reps_button.place(
    x=430.0,
    y=93.0,
    width=273.0,
    height=182.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
body_weight_button = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: [print("body weight clicked"), run_script("bw_gui.py")],
    relief="flat"
)
body_weight_button.place(
    x=225.0,
    y=281.0,
    width=350.0,
    height=201.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    400.0,
    581.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#2D3F55",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=0.0,
    y=563.0,
    width=800.0,
    height=35.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
folder_loc_button = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: [print("folder_loc clicked")],
    relief="flat"
)
folder_loc_button.place(
    x=648.0,
    y=539.0,
    width=127.0,
    height=48.0
)

root.resizable(False, False)
root.mainloop()
